[workspace]
authors = ["Butterfingrz <2395959141@qq.com>"]

channels = ["https://srgconda.bj.bcebos.com/",
            "https://prefix.dev/meta-forge",
            "conda-forge",
            "file:///home/jovyan/meta-forge/output"
]

name = "100-days-of-DSL"
platforms = ["linux-64"]
version = "0.1.0"

[system-requirements]
cuda = "12.9"

[activation]
env = { CUDA_HOME = "$CONDA_PREFIX" }

[dependencies]
python = "3.12.*"
cuda = "12.9.*"
pytorch = "*"
apache-tvm-ffi = { version = "*", channel = "https://srgconda.bj.bcebos.com/" }
nvidia-cutlass-dsl = { version = "*", channel = "https://srgconda.bj.bcebos.com/" }
tilelang = { version = "*", channel = "file:///home/jovyan/meta-forge/output" }
# torch-c-dlpack-ext= { version = "*", channel = "https://srgconda.bj.bcebos.com/"}

jupyterlab = "*"
ipykernel = "*"

ipywidgets = "*"        # 交互式小部件
matplotlib = "*"        # 图表内联显示
nbformat = "*"          # notebook 格式支持